trigger:
- master
variables:
  azureSubscription: '#210000001C1737# Kst 195510 - SC-HUB DEV(4903d38f-fec1-4a2c-bd9f-79bb9eda788b)'
  downloadedFile: 'basicpolicywithcoy2.csv'
  destinationPath: '$(Build.ArtifactStagingDirectory)\$downloadedFile'

pool:
  vmImage: 'windows-latest'

stages:
- stage: GenerateSAS
  jobs:
  - job: GenerateSAS
    displayName: 'Generate SAS Token'
    steps:
    - checkout: self
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '3.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet
        performMultiLevelLookup: true

    - task: PowerShell@2
      displayName: 'Install Az module'
      inputs:
        targetType: 'inline'
        script: 'Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser'

    - task: PowerShell@2
      displayName: 'Generate SAS'
      inputs:
        targetType: 'filepath'
        filePath: 'sas.ps1'
        arguments: '-destinationPath $(destinationPath) -servicePrincipalId $(servicePrincipalId) -servicePrincipalKey $(servicePrincipalKey) -tenantId $(tenantId) -storageAccountName $(storageAccountName) -containerName $(containerName) -blobName $(blobName) -sasPermissions $(sasPermissions) -sasExpiry $(sasExpiry)'
      env:
        servicePrincipalTenantId: $(servicePrincipalTenantId)
        servicePrincipalId: $(servicePrincipalId)
        servicePrincipalKey: $(servicePrincipalKey) 

  - job: DownloadBlob
    displayName: 'Download CSV Blob'
    dependsOn: GenerateSAS
    steps:
    - task: PowerShell@2
      displayName: 'Download CSV'
      inputs:
        targetType: 'filepath'
        filePath: 'download.ps1'
        arguments: '-downloadedFile $(downloadedFile) -containerName $(containerName) -blobName $(blobName) -storageAccountName $(storageAccountName)'
    
         

